#!/system/bin/sh
# chmod -R 755 /su/su.d /sbin/supersu/su.d
#
# Systemless Media Replacement Mounts
# osm0sis @ xda-developers

sumnt=$(ls /su || ls /sbin/supersu) 2>/dev/null;

mount -o bind $sumnt/media /system/media;

