#!/system/bin/sh
# chmod -R 755 /magisk/.core/service.d /sbin/.core/img/.core/service.d /sbin/.magisk/img/.core/service.d /data/adb/service.d/000mediacleanup
#
# Systemless Media Post-Uninstall Cleanup
# osm0sis @ xda-developers

if [ ! -e /magisk/nexusmedia -a ! -e /sbin/.core/img/nexusmedia -a ! -e /sbin/.magisk/img/nexusmedia -a ! -e /data/adb/modules/nexusmedia ]; then
  rm -f /cache/magisk_mount/system/media/bootanimation.zip /data/adb/magisk_simple/system/media/bootanimation.zip;
  cd /cache;
  rmdir -p magisk_mount/system/media;
  cd /data/adb;
  rmdir -p magisk_simple/system/media;
  rm -f /magisk/.core/service.d/000mediacleanup /sbin/.core/img/.core/service.d/000mediacleanup /sbin/.magisk/img/.core/service.d/000mediacleanup /data/adb/service.d/000mediacleanup;
fi;

