#!/system/bin/sh
# chmod -R 755 /magisk/.core/service.d /sbin/.core/img/.core/service.d
#
# Systemless Media Post-Uninstall Cleanup
# osm0sis @ xda-developers

if [ ! -e /magisk/nexusmedia -a ! -e /sbin/.core/img/nexusmedia ]; then
  rm -f /cache/magisk_mount/system/media/bootanimation.zip;
  cd /cache;
  rmdir -p magisk_mount/system/media;
  rm -f /magisk/.core/service.d/000mediacleanup /sbin/.core/img/.core/service.d/000mediacleanup;
fi;

